### ISSUE TITLE
BOM file

### ISSUE THREAD

**Issue by olivierjan** [Markeno76/rgbi2rgba#1]
Hi, first, many thanks for this great design. 
I've been looking at the repo and I can't seem to find the BOM for this project. There is one on your website (https://hobbytronics.home.blog/2023/02/07/commodore-128-80-column-or-cga-rgbi-to-rgba-15khz-vga-adapter-part-2/) but is it up-to-date ? 
Regards, 
Olivier

**Comment by t9999clint** [comment]
I'm also looking to build one of these to use with my PCjr and my GBS-Control. A BOM would be super handy for this.

**Comment by Markeno76** [comment]
The "Parts list" section on Part 2 is accurate for the current design.  The changes from from the board shown in the article are corrections to the layout etc, not parts changes.   I have switched to using the adapter with a GBS Control, as I found the SCART to HDMI adapter I had been using previously was not being stable on certain programs, I don't know why.  It is also reported as laggy, so I switched to the GBS Control.  The GBS Control doesn't need the CSync function and I set up the adapter to not do CSync.

**Comment by Markeno76** [comment]
BOM Added that is a bit more complete than the Blog post, but I can't say where to get a 8Pin "U" DIN connector if you want to use it with the C128.  The Power Jack is not specific to a part number, but all the generic 2.5x5.5mm through hole mount power jacks I have come across fit the footprint.
